"""
Audio Deepfake & Synthetic Speech Artifact Scorer.

Combines acoustic feature extraction (spectral tilt, pitch variance, high-frequency phase anomaly)
with optional pretrained model evaluation (AASIST / Wav2Vec2) to output a confidence score (0.0 to 1.0)
that the audio was generated by a TTS / voice clone model.

Note: Presented explicitly as an INDICATION (not absolute proof) per ScamGuard's honest-accuracy policy.
"""
import os
import tempfile
import numpy as np
from typing import Tuple, List
from app.config import settings
from app.core.schemas import AudioAnalysisResult


def _extract_acoustic_features(y: np.ndarray, sr: int) -> dict:
    """
    Extracts acoustic signals commonly anomalous in neural TTS / voice clones:
    - Spectral flatness (TTS often over-smoothed in upper frequencies)
    - Zero crossing rate variance (micro-tremors in natural breath vs synthetic)
    - Pitch (F0) std-dev (flat or mechanical intonation)
    """
    if len(y) == 0:
        return {"flatness": 0.0, "zcr_std": 0.0, "pitch_std": 0.0}

    try:
        import librosa
        flatness = float(np.mean(librosa.feature.spectral_flatness(y=y)))
        zcr = librosa.feature.zero_crossing_rate(y=y)
        zcr_std = float(np.std(zcr))

        # Pitch contour (pyin or pitch tracking)
        try:
            pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
            pitch_vals = pitches[magnitudes > np.median(magnitudes)]
            pitch_std = float(np.std(pitch_vals)) if len(pitch_vals) > 0 else 0.0
        except Exception:
            pitch_std = 0.0

        return {"flatness": flatness, "zcr_std": zcr_std, "pitch_std": pitch_std}
    except Exception as e:
        print(f"[audio.deepfake] Feature extraction error: {e}")
        return {"flatness": 0.0, "zcr_std": 0.0, "pitch_std": 0.0}


def score_audio_bytes(audio_bytes: bytes, suffix: str = ".wav") -> Tuple[float, List[str]]:
    """
    Scores audio bytes for synthetic/deepfake speech indications.
    Returns (deepfake_score: float 0-1, indications: list[str]).
    """
    if not settings.deepfake_enabled or not audio_bytes:
        return 0.0, []

    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(audio_bytes)
        tmp_path = tmp.name

    try:
        import librosa
        y, sr = librosa.load(tmp_path, sr=16000, mono=True)
    except Exception as e:
        print(f"[audio.deepfake] Error loading audio: {e}")
        return 0.0, []
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    if len(y) < 1600:  # < 0.1s
        return 0.0, []

    features = _extract_acoustic_features(y, sr)
    score = 0.0
    indications = []

    # Heuristic scoring based on TTS spectral signatures
    # 1. Unnatural spectral flatness (too low = muffled/over-smoothed TTS; too high = robotic noise)
    if features["flatness"] < 0.0005:
        score += 0.35
        indications.append("Over-smoothed spectral envelope (characteristic of neural TTS vocoder)")
    elif features["flatness"] > 0.08:
        score += 0.25
        indications.append("Unnatural high-frequency spectral noise")

    # 2. Pitch monotonicity (synthetic voices often lack natural micro-inflection)
    if 0.0 < features["pitch_std"] < 15.0:
        score += 0.35
        indications.append("Flat/robotic pitch contour (low fundamental frequency variance)")

    # 3. ZCR unnatural uniformity
    if features["zcr_std"] < 0.01:
        score += 0.20
        indications.append("Absence of natural micro-breath / unvoiced consonant variance")

    final_score = min(round(score, 3), 0.95)
    return final_score, indications
